ALTER TABLE bill
  ADD PRIMARY KEY (B_ID),
  ADD CONSTRAINT c_fid FOREIGN KEY (C_ID) REFERENCES customers (C_ID) ON DELETE CASCADE;

ALTER TABLE contains
  ADD PRIMARY KEY (STORE_ID,ITEM_ID),
  ADD CONSTRAINT i_fid1 FOREIGN KEY (ITEM_ID) REFERENCES items (ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT store_fid1 FOREIGN KEY (STORE_ID) REFERENCES store (STORE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE customers
  ADD PRIMARY KEY (C_ID),
  ADD CONSTRAINT e_fid FOREIGN KEY (E_ID) REFERENCES employee (E_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE employee
  ADD PRIMARY KEY (E_ID);

ALTER TABLE items
  ADD PRIMARY KEY (ITEM_ID);

ALTER TABLE item_category
  ADD PRIMARY KEY (ITEM_ID);
  ADD CONSTRAINT item_fid FOREIGN KEY (ITEM_ID) REFERENCES items (ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE orders
  ADD PRIMARY KEY (C_ID,ITEM_ID),
  ADD CONSTRAINT c_fid2 FOREIGN KEY (C_ID) REFERENCES customers (C_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT item_fid2 FOREIGN KEY (ITEM_ID) REFERENCES items (ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE shipment
  ADD PRIMARY KEY (SHIP_ID),
  ADD CONSTRAINT shipment_fid FOREIGN KEY (SHIP_ID) REFERENCES ships (SHIP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT store_fid FOREIGN KEY (STORE_ID) REFERENCES store (STORE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ships
  ADD PRIMARY KEY (SUPP_ID,SHIP_ID),
  ADD CONSTRAINT supp_fid FOREIGN KEY (SUPP_ID) REFERENCES suppliers (SUPP_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE store
  ADD PRIMARY KEY (STORE_ID),
  ADD CONSTRAINT mgr_fid FOREIGN KEY (MGR_ID) REFERENCES employee (E_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE suppliers
  ADD PRIMARY KEY (SUPP_ID);